#!/bin/sh
#aconnect -i -o | sed -n 's/\(client.*\x27\)\(.*\)\(\x27.*\)/\2/p' | sed -n '/\(System\|Midi Through\)/!p'
#amidi -l | awk 'NR > 1 {$1=$2=""; print $0}' | sed 's/\(^  \)\(.*\)/\2/'

progname=$0

usage () {
   cat <<EOF
Usage: $progname [-n]
EOF
   exit 0
}

while getopts ":n" opt; do
   case $opt in

   n )  amidi -l 2> /dev/null | awk 'NR > 1 {$1=$2=""; print $0}' | sed 's/\(^  \)\(.*\)/\2/' | wc -l
	exit 0
	;;
   \?)  usage 
	exit 0
	;;
   esac
done
amidi -l | awk 'NR > 1 {$1=$2=""; print $0}' | sed 's/\(^  \)\(.*\)/\2/'



