#!/usr/bin/python

import liblo, sys

# send all messages to port 56418 on the local machine
try:
#    target = liblo.Address("osc.udp://127.0.0.1:56419")
    target = liblo.Address(56419)
except liblo.AddressError, err:
    print str(err)
    sys.exit()

#check for message i arguments
if len(sys.argv)<2:
   print "displaymsg: No message to display"
   sys.exit()
else:
   oscPath = "/system/msg"
   msg = sys.argv[1]

if len(sys.argv)==3: 
   if sys.argv[2]=="--preview":
	oscPath = "/system/preview/text"
   else:
	print "displaymsg: Ignoring unknown option - " + sys.argv[2]
	

# send message "/system/msg" with a string argument
try:
    liblo.send(target, oscPath, msg)
except:
   print("displaymsg: Unable to send OSCmessage ", sys.exc_info()[0])
