#!/usr/bin/python

import liblo, sys

# send all messages to port 56418 on the local machine
try:
#    target = liblo.Address("osc.udp://127.0.0.1:56419")
    target = liblo.Address(56418)
except liblo.AddressError, err:
    print str(err)
    sys.exit()


# send quit message
try:
    liblo.send(target, "/mididings/quit")
except:
   print("Error")
